### PR TITLE
Add CVARs to draw individual crosshair lines

### PR DESCRIPTION
**Pull request by dxtzero**
add a cvar for each of the crosshair lines so that they can be individually drawn or not.

### CODE REVIEW

**Comment by YaLTeR** [comment]
What's the point?

**Comment by dxtzero** [comment]
i dont like vertical lines in my crosshairs, maybe someone doesnt like horizontal lines, maybe they want the left and bottom lines only, or some other combination?

#29 could benefit from this.

is there a reason not to have this? (im not sure how to convey a tone of being inquisitive and not antagonistic with that question)

**Comment by YaLTeR** [comment]
My only concern is that it adds complexity, but I guess it's fine.

**Comment by dxtzero** [comment]
i hope not too much :)

thanks!

**Pull request merged**
