### PR TITLE
Add build instructions for Visual Studio 2022 Preview

### PR DESCRIPTION
**Pull request by sabianroberts**
After testing OpenAG in the VS2022 preview, and having confirmed that [it does build on the latest VS2022/C++ 20 compilers,](https://imgur.com/a/2hB4dI6) I thought I'd add the build instructions for it.

~~I've placed it below VS2017 as chances are slim people will want to use pre-release beta software to develop OpenAG; but the instructions are there should they wish to do so. Editors may want to edit it above VS2019 once VS2022 fully releases~~

### CODE REVIEW

**Comment by YaLTeR** [comment]
This doesn't seem any different to VS2019, what's the point?

**Comment by sabianroberts** [comment]
Hm, could maybe just add "Visual Studio 2019 & Visual Studio 2022" to the instructions

**Comment by YaLTeR** [comment]
Sure, "Visual Studio 2019 & 2022" should work

**Comment by YaLTeR** [comment]
Sorry, haven't noticed the update.

**Pull request merged**
