### PR TITLE
Add packet loss indicator in scoreboard

### PR DESCRIPTION
**Pull request by execut4ble**
lol 3 commits because im bög and skrew up kode blät))

### CODE REVIEW

**Comment by YaLTeR** [comment]
Is this actually useful?

**Comment by execut4ble** [comment]
Yes, useful if you want to see how much loss noi has to make his whining justified.

Other than that, vanilla AG has it, so why not.

**Comment by YaLTeR** [comment]
AG has an IRC client, so why not add that as well. I'm cleaning stuff up in process.

**Comment by execut4ble** [comment]
Still useful to see if you or your opponent is lagging.

**Pull request closed without merging**
