### PR TITLE
[appveyor.yml] Use proper configuration matrix

### PR DESCRIPTION
**Pull request by Margen67**

### CODE REVIEW

**Comment by YaLTeR** [comment]
Hm?

**Comment by Margen67** [comment]
oops

**Comment by YaLTeR** [comment]
Is this stated in the docs or something? Could you link?

**Comment by Margen67** [comment]
https://www.appveyor.com/docs/appveyor-yml/
```
# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release
```

**Comment by YaLTeR** [comment]
Thing is, this isn't building a regular .sln, but rather passing the environment variable to CMake. I suspect your change won't work.

**Comment by YaLTeR** [comment]
Even if this somehow works, I prefer the current approach because I'm explicitly using the `CONFIGURATION` environment variable to the `cmake` command, so I'd rather explicitly set it as an environment variable.

**Comment by Margen67** [comment]
I'm pretty sure this method should still have the environment variable set.

**Pull request closed without merging**
